# Generated by Django 5.0.1 on 2024-02-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
