# Generated by Django 5.0.1 on 2024-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_alter_taskmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
